" .vimrc
" Author: slash
" Source: TBA

runtime bundle/pathogen/autoload/pathogen.vim

" Preamble
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on
set nocompatible

" Basic options
set encoding=utf-8	
set modelines=0
set autoindent
set showmode
set showcmd
set hidden
set visualbell
set ttyfast
set ruler
set backspace=indent,eol,start
set nonumber
set norelativenumber
set laststatus=2
set history=1000
set undofile
set undoreload=10000
"set list
"set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮
set shell=/bin/bash
set lazyredraw
set matchtime=3
set showbreak=↪
set splitbelow
set splitright
set fillchars=diff:⣿,vert:│
set autowrite
set autoread
set shiftround
set title
set linebreak

" Tabs, spaces, wrapping
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set wrap
set textwidth=80
set formatoptions=qrn1
set colorcolumn=+1

" Color scheme
syntax on
set background=dark
colorscheme solarized

" Environments
set mouse=a

" first thing's first, disable those damn arrow keys (in insert mode too)
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" remap the leader keys
let mapleader = "."
let maplocalleader = "\\"

" timeout settings
set notimeout
set ttimeout
set ttimeoutlen=10

" map F2 to resource .vimrc
noremap <F2> :source ~/.vimrc<cr>
inoremap <F2> <esc>:source ~/.vimrc<cr>

" toggle line numbers (<leader>n) and relative numbers (<leader>r)
nnoremap <leader>n :setlocal number!<cr>
nnoremap <leader>r :setlocal relativenumber!<cr>

" map goto non blank char, last non blank char
noremap H ^
noremap L $
vnoremap L g_

" set cursor and column lines everyware except insert mode
set cursorline
set cursorcolumn

augroup mymarkers
    autocmd!
    autocmd InsertEnter * set nocursorline nocursorcolumn
    autocmd InsertLeave * set cursorline cursorcolumn
augroup end

" save current file when the focus is lost
autocmd FocusLost * :silent! wall

" enable auto save on no key pressed
autocmd CursorHold * :wall

" searching
nnoremap / /\v
vnoremap / /\v

set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
set gdefault

set scrolloff=3
set sidescroll=1
set sidescrolloff=10

" NERDTree Toggle on <F1>
noremap  <F1> :NERDTreeToggle<cr>
inoremap <F1> <esc>:NERDTreeToggle<cr>
